# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'DBSwift' do

pod 'Alamofire', '~> 4.4'
pod 'Kingfisher', '~> 4.6.1'
pod 'HandyJSON', '~> 4.0.0-beta.1'
end
